server:
  port: 7070
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: 123456

  kafka:
    bootstrapServers:
      - 127.0.0.1:9092
    consumer:
      auto-offset-reset: earliest
      valueDeserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
      max:
        poll:
          interval:
            ms: 300000
      enable-auto-commit: false
    producer:
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer

    listener:
      missing-topics-fatal: false
      ack-mode: MANUAL_IMMEDIATE

mybatis:
  mapper-locations: classpath:mapper/*.xml  # XML映射文件位置
  type-aliases-package: com.csdn.dt.kafka.model   # 实体类包路径
  configuration:
    map-underscore-to-camel-case: true      # 开启驼峰命名转换